function val(id){return document.getElementById(id).value}
function sev(s){s=Number(s);if(s>=9)return 'Critical';if(s>=7)return 'High';if(s>=4)return 'Medium';if(s>0)return 'Low';return 'None'}
function yes(id){return val(id)=='yes'}
function calc(){var base=Number(String(val('base_score')||'0').replace(',','.'));var score=base;var r=[];if(yes('internet_exposed')){score+=0.4;r.push('internet exposure increased environmental risk')}else{score-=0.3;r.push('absence of internet exposure reduced environmental risk')}if(yes('network_segmented')){score-=0.7;r.push('network segmentation reduced reachable attack surface')}if(yes('firewall_restricted')){score-=0.5;r.push('firewall restrictions reduced exposure')}if(yes('compensating_controls')){score-=0.4;r.push('compensating controls reduced expected impact')}if(yes('pci_in_scope')){score+=0.3;r.push('PCI scope increased business and compliance relevance')}var c=val('business_criticality');if(c=='high'){score+=0.4;r.push('high business criticality increased environmental relevance')}if(c=='low'){score-=0.2;r.push('low business criticality reduced environmental relevance')}var env=Math.max(0,Math.min(10,score));env=Number(env.toFixed(1));var delta=Number((env-base).toFixed(1));var decision=delta<0?'downgraded':(delta>0?'upgraded':'unchanged');var out={scenario:val('scenario'),asset_id:val('asset_id'),cve:val('cve'),base_score:base.toFixed(1),base_severity:sev(base),environmental_score:env.toFixed(1),environmental_severity:sev(env),delta:delta.toFixed(1),decision:decision,rationale:r.join('; '),internet_exposed:val('internet_exposed'),network_segmented:val('network_segmented'),pci_in_scope:val('pci_in_scope'),firewall_restricted:val('firewall_restricted'),compensating_controls:val('compensating_controls'),business_criticality:c};window.lastCvssResult=out;document.getElementById('result').innerHTML='<h3>Result</h3><div class=grid><div class=card><div>Base</div><div class=metric>'+out.base_score+'</div><div>'+out.base_severity+'</div></div><div class=card><div>Environmental</div><div class=metric>'+out.environmental_score+'</div><div>'+out.environmental_severity+'</div></div><div class=card><div>Delta</div><div class=metric>'+out.delta+'</div><div>'+out.decision+'</div></div></div><p class=note>'+out.rationale+'</p><textarea rows=10 id=exportBox>'+JSON.stringify(out,null,2)+'</textarea>'}
function loadExample(){document.getElementById('scenario').value='pci_segmented_lab_20260517_143146';document.getElementById('asset_id').value='payment-api';document.getElementById('cve').value='CVE-2025-0001';document.getElementById('base_score').value='9.8';document.getElementById('internet_exposed').value='no';document.getElementById('network_segmented').value='yes';document.getElementById('pci_in_scope').value='yes';document.getElementById('firewall_restricted').value='yes';document.getElementById('compensating_controls').value='yes';document.getElementById('business_criticality').value='high';calc()}
function downloadJson(){var data=JSON.stringify(window.lastCvssResult||{},null,2);var blob=new Blob([data],{type:'application/json'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cvss_environmental_result.json';a.click()}
window.addEventListener('DOMContentLoaded',loadExample)

function downloadCsv(){var r=window.lastCvssResult||{};var h=['scenario','asset_id','cve','base_score','base_severity','environmental_score','environmental_severity','delta','decision','rationale'];var line=h.map(function(k){return String(r[k]||'').replaceAll(',',';')}).join(',');var blob=new Blob([h.join(',')+'
'+line],{type:'text/csv'});var a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='cvss_environmental_result.csv';a.click();}
function copyPipelineJson(){var r=window.lastCvssResult||{};var pkg={case_description:{scenario:r.scenario,source:'interactive_static_mvp'},vulnerabilities:[{finding_id:'interactive-001',asset_id:r.asset_id,cve:r.cve,vulnerability_type:'user supplied',base_score:r.base_score,base_severity:r.base_severity,base_vector:'',internet_exposed:r.internet_exposed,network_segmented:r.network_segmented,pci_in_scope:r.pci_in_scope,firewall_restricted:r.firewall_restricted,compensating_controls:r.compensating_controls,business_criticality:r.business_criticality,notes:r.rationale}],result:r};navigator.clipboard.writeText(JSON.stringify(pkg,null,2));alert('Pipeline-compatible JSON copied to clipboard');}
