"""Generate JSON, CSV, JSONL and Markdown reports."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Dict, List


def write_outputs(rows: List[Dict[str, Any]], out_dir: str | Path) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    (out / "assessments.json").write_text(json.dumps(rows, indent=2), encoding="utf-8")

    with (out / "summary.csv").open("w", encoding="utf-8", newline="") as f:
        fieldnames = [
            "finding_id",
            "asset_id",
            "cve",
            "vulnerability_type",
            "state",
            "base_score",
            "environmental_score",
            "official_cvss_base_score",
            "official_cvss_base_severity",
            "contextual_score",
            "contextual_severity",
            "contextual_decision",
            "contextual_delta_from_official_base",
            "cr",
            "ir",
            "ar",
            "mav",
            "matches_expected_requirements",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            env = r.get("environmental_metrics", {})
            official = r.get("official_cvss") if isinstance(r.get("official_cvss"), dict) else {}
            contextual = r.get("contextual_environmental") if isinstance(r.get("contextual_environmental"), dict) else {}
            writer.writerow({
                "finding_id": r.get("finding_id"),
                "asset_id": r.get("asset_id"),
                "cve": r.get("cve"),
                "vulnerability_type": r.get("vulnerability_type"),
                "state": r.get("state"),
                "base_score": r.get("base_score"),
                "environmental_score": r.get("environmental_score"),
                "official_cvss_base_score": official.get("base_score", r.get("base_score")),
                "official_cvss_base_severity": official.get("base_severity", r.get("base_severity")),
                "contextual_score": contextual.get("contextual_score", r.get("contextual_score", r.get("environmental_score"))),
                "contextual_severity": contextual.get("contextual_severity", r.get("contextual_severity", r.get("environmental_severity"))),
                "contextual_decision": contextual.get("decision", r.get("contextual_decision")),
                "contextual_delta_from_official_base": contextual.get("delta_from_official_base", r.get("delta_from_official_base")),
                "cr": env.get("CR"),
                "ir": env.get("IR"),
                "ar": env.get("AR"),
                "mav": env.get("MAV"),
                "matches_expected_requirements": r.get("matches_expected_requirements"),
            })

    with (out / "audit_trace.jsonl").open("w", encoding="utf-8") as f:
        for r in rows:
            evidence_value = r.get("evidence", [])
            if isinstance(evidence_value, dict):
                evidence_items = [evidence_value]
            else:
                evidence_items = [item for item in evidence_value if isinstance(item, dict)]
            for evidence in evidence_items:
                f.write(json.dumps({
                    "finding_id": r.get("finding_id"),
                    "asset_id": r.get("asset_id"),
                    "cve": r.get("cve"),
                    "state": r.get("state"),
                    **evidence,
                }, ensure_ascii=False) + "\n")

    (out / "report.md").write_text(_markdown_report(rows), encoding="utf-8")


def _markdown_report(rows: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    lines.append("# AI Bridge CVSS Environmental Assessment Report\n")
    lines.append("This report was generated by the deterministic starter prototype.\n")
    lines.append("## Summary Table\n")
    lines.append("| Finding | State | Asset | CVE | Type | Official CVSS Base | Official Severity | Contextual Score | Contextual Severity | Contextual Decision | CR | IR | AR | MAV | Expected? |")
    lines.append("|---|---|---|---|---|---:|---|---:|---|---|---:|---:|---:|---:|---:|")
    for r in rows:
        env = r.get("environmental_metrics", {})
        official = r.get("official_cvss") if isinstance(r.get("official_cvss"), dict) else {}
        contextual = r.get("contextual_environmental") if isinstance(r.get("contextual_environmental"), dict) else {}
        official_base = official.get("base_score", r.get("base_score"))
        official_severity = official.get("base_severity", r.get("base_severity"))
        contextual_score = contextual.get("contextual_score", r.get("contextual_score", r.get("environmental_score")))
        contextual_severity = contextual.get("contextual_severity", r.get("contextual_severity", r.get("environmental_severity")))
        contextual_decision = contextual.get("decision", r.get("contextual_decision"))
        lines.append(
            f"| {r.get('finding_id')} | {r.get('state')} | {r.get('asset_id')} | {r.get('cve')} | "
            f"{r.get('vulnerability_type')} | {official_base} | {official_severity} | "
            f"{contextual_score} | {contextual_severity} | {contextual_decision} | "
            f"{env.get('CR')} | {env.get('IR')} | {env.get('AR')} | {env.get('MAV')} | "
            f"{r.get('matches_expected_requirements')} |"
        )

    lines.append("\n## Terminology\n")
    lines.append("Official CVSS fields come from the official CVSS vector. Contextual fields are operational prioritization outputs and must not be labeled as official CVSS.\n")
    lines.append("\n## Auditability\n")
    lines.append("See `audit_trace.jsonl` for row-level evidence used by the assessment.\n")
    return "\n".join(lines) + "\n"
