"""Generate JSON, CSV, JSONL and Markdown reports."""

from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Dict, List


def write_outputs(rows: List[Dict[str, Any]], out_dir: str | Path) -> None:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)

    (out / "assessments.json").write_text(json.dumps(rows, indent=2), encoding="utf-8")

    with (out / "summary.csv").open("w", encoding="utf-8", newline="") as f:
        fieldnames = [
            "finding_id",
            "asset_id",
            "cve",
            "vulnerability_type",
            "state",
            "base_score",
            "environmental_score",
            "cr",
            "ir",
            "ar",
            "mav",
            "matches_expected_requirements",
        ]
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for r in rows:
            env = r["environmental_metrics"]
            writer.writerow({
                "finding_id": r["finding_id"],
                "asset_id": r["asset_id"],
                "cve": r["cve"],
                "vulnerability_type": r["vulnerability_type"],
                "state": r["state"],
                "base_score": r["base_score"],
                "environmental_score": r["environmental_score"],
                "cr": env.get("CR"),
                "ir": env.get("IR"),
                "ar": env.get("AR"),
                "mav": env.get("MAV"),
                "matches_expected_requirements": r["matches_expected_requirements"],
            })

    with (out / "audit_trace.jsonl").open("w", encoding="utf-8") as f:
        for r in rows:
            for evidence in r["evidence"]:
                f.write(json.dumps({
                    "finding_id": r["finding_id"],
                    "asset_id": r["asset_id"],
                    "cve": r["cve"],
                    "state": r["state"],
                    **evidence,
                }, ensure_ascii=False) + "\n")

    (out / "report.md").write_text(_markdown_report(rows), encoding="utf-8")


def _markdown_report(rows: List[Dict[str, Any]]) -> str:
    lines: List[str] = []
    lines.append("# AI Bridge CVSS Environmental Assessment Report\n")
    lines.append("This report was generated by the deterministic starter prototype.\n")
    lines.append("## Summary Table\n")
    lines.append("| Finding | State | Asset | CVE | Type | Base | Environmental | CR | IR | AR | MAV | Expected? |")
    lines.append("|---|---|---|---|---:|---:|---:|---:|---:|---:|---:|---:|")
    for r in rows:
        env = r["environmental_metrics"]
        lines.append(
            f"| {r['finding_id']} | {r['state']} | {r['asset_id']} | {r['cve']} | "
            f"{r['vulnerability_type']} | {r['base_score']} | {r['environmental_score']} | "
            f"{env.get('CR')} | {env.get('IR')} | {env.get('AR')} | {env.get('MAV')} | "
            f"{r['matches_expected_requirements']} |"
        )

    lines.append("\n## Evidence Trace\n")
    for r in rows:
        lines.append(f"### {r['finding_id']} / {r['state']} / {r['cve']}\n")
        lines.append(f"- Environmental vector: `{r['environmental_vector']}`")
        for e in r["evidence"]:
            lines.append(f"- `{e['metric']}` from `{e['source']}`: {e['reason']}")
        lines.append("")
    return "\n".join(lines)
