import { getDashboardData } from "@/lib/data";
export const dynamic = "force-dynamic";
function fmt(value: number) { return value.toFixed(1); }
export default async function Home() {
  const data = await getDashboardData();
  const manifest = data.manifest as any;
  return (
    <main className="page">
      <section className="hero"><div><div className="eyebrow">AI Bridge / Watcher Artifact</div><h1 className="title">CVSS Environmental Dashboard</h1><p className="subtitle">Interactive cloud-ready view of the PCI segmented lab run. The dashboard connects local environmental evidence, CVSS Environmental labels, before-after score deltas, and audit-trace material used by the manuscript.</p></div><div className="card mono"><div className="label">Latest run</div><div>{data.runId}</div><div className="label" style={{ marginTop: 12 }}>Case</div><div>{data.caseId}</div><div className="label" style={{ marginTop: 12 }}>Data source</div><div><span className="badge unchanged">{data.source}</span></div><div className="label" style={{ marginTop: 12 }}>{data.sourceDetail}</div></div></section>
      <section className="grid cards"><div className="card"><div className="metric">{data.metrics.findings}</div><div className="label">Findings</div></div><div className="card"><div className="metric">{data.metrics.assessments}</div><div className="label">Assessments</div></div><div className="card"><div className="metric">{data.metrics.downgraded}</div><div className="label">Downgraded</div></div><div className="card"><div className="metric">{data.metrics.unchanged}</div><div className="label">Unchanged</div></div><div className="card"><div className="metric">{data.metrics.meanDelta.toFixed(3)}</div><div className="label">Mean delta</div></div></section>
      <section className="panel"><h2>Before/after environmental effects</h2><div className="table-wrap"><table><thead><tr><th>Finding</th><th>Asset</th><th>CVE</th><th>Type</th><th>Before</th><th>After</th><th>Delta</th><th>MAV</th><th>Effect</th></tr></thead><tbody>{data.comparison.map((row: any) => (<tr key={row.finding_id}><td className="mono">{row.finding_id}</td><td>{row.asset_id}</td><td className="mono">{row.cve}</td><td>{row.vulnerability_type}</td><td>{fmt(row.environmental_before)}</td><td>{fmt(row.environmental_after)}</td><td>{row.delta.toFixed(1)}</td><td className="mono">{row.mav_before} to {row.mav_after}</td><td><span className={`badge ${row.effect}`}>{row.effect}</span></td></tr>))}</tbody></table></div></section>
      <section className="grid two"><div className="panel"><h2>Assessment rows</h2><div className="table-wrap"><table><thead><tr><th>Finding</th><th>State</th><th>Asset</th><th>Base</th><th>Env</th><th>CR</th><th>IR</th><th>AR</th><th>MAV</th><th>Expected</th></tr></thead><tbody>{data.summary.map((row: any) => (<tr key={`${row.finding_id}-${row.state}`}><td className="mono">{row.finding_id}</td><td>{row.state}</td><td>{row.asset_id}</td><td>{row.base_score.toFixed(1)}</td><td>{row.environmental_score.toFixed(1)}</td><td>{row.cr}</td><td>{row.ir}</td><td>{row.ar}</td><td>{row.mav}</td><td>{row.matches_expected_requirements}</td></tr>))}</tbody></table></div></div><div className="panel"><h2>Run manifest</h2><p className="label">Input hashes make the run reproducible and auditable.</p><div className="metric">{manifest.case_files?.length ?? 0}</div><div className="label">case files hashed</div><div className="footer mono">Generated: {manifest.generated_at_utc ?? "n/a"}</div><div className="footer mono">Max abs delta: {manifest.summary?.max_abs_delta ?? "n/a"}</div></div></section>
      <section className="panel audit"><h2>Audit trace sample</h2><pre>{JSON.stringify(data.auditTrace.slice(0, 12), null, 2)}</pre></section>
      <div className="footer">Cloud target: Vercel frontend with Railway PostgreSQL persistence. Current page is seeded from the latest deterministic run and ready to be connected to the database after Railway provisioning.</div>
    </main>
  );
}
